name: Build & Deploy
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: npm install
    - run: npm run compile
    - run: npm run compile:min
    - run: mkdir -p build
    - run: cp -r reset.* ./build

    - name: Create Index.html
      working-directory: build
      run: |
        cat > index.html << EOF
        <!DOCTYPE html><html lang="en">
        <head>
          <title>reset-css</title>
          <meta name="description" content="A tiny modern CSS reset.">
          <link rel="stylesheet" type="text/css" href="reset.min.css" />
        </head>
        <body style="text-align: center;">
          <a href="https://github.com/uiwjs/reset-css" target="__blank">
            <h1 style="font-size: 46px; padding: 50px 0 0 0; font-weight: bold;">reset.css</h1>
          </a>
          <p style="padding-bottom: 30px;color: #a5a5a5;">A tiny modern CSS reset.</p>
          <div>
            <a href="./reset.css">reset.css</a>
          </div>
          <div>
            <a href="./reset.less">reset.less</a>
          </div>
          <div>
            <a href="./reset.min.css">reset.min.css</a>
          </div>
        </body></html>
        EOF

    - run: git status
    - run: npm install @jsdevtools/npm-publish -g
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./package.json

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build