name: Build & Deploy
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - run: npm install
    - run: npm run compile
    - run: npm run compile:min
    - run: mkdir -p build
    - run: cp -r reset.* ./build

    - name: Create Index.html
      working-directory: build
      run: |
        cat > index.html << EOF
        <!DOCTYPE html><html lang="en">
        <head>
          <title>reset-css</title>
          <meta name="description" content="A tiny modern CSS reset.">
        </head>
        <body>
          <div>
            <a href="./reset.css">reset.css</a>
          </div>
          <div>
            <a href="./reset.less">reset.less</a>
          </div>
          <div>
            <a href="./reset.min.css">reset.min.css</a>
          </div>
        </body></html>
        EOF

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build