name: Publish Package to npmjs
on:
  release:
    types: [created]

jobs:
  github-publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@uiwjs'

      - run: |
          node -e 'var pkg = require("./package.json"); pkg.version="@uiwjs/reset-css"; pkg.publishConfig = { "registry": "https://npm.pkg.github.com/" }; require("fs").writeFileSync("./package.json", JSON.stringify(pkg, null, 2))'

      - run: npm install
      - run: ls -al
      - run: cat ./package.json
      - run: npm run compile
      - run: npm run compile:min
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm-publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install
      - run: npm run compile
      - run: npm run compile:min

      - name: 📦 @uiw/reset.css publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
